defmodule Arena.Map.TileSemanticsTest do
  @moduledoc """
  The rule the Rust client is held to, tested where it lives.

  `client-rs/crates/ao-core/fixtures/tile_semantics.txt` is generated by calling the same
  functions this file tests, so a change to the rule shows up in three places at once: here,
  in the fixture diff, and in the Rust test that reads it. That is the point — the previous
  arrangement had the rule written out once inline in `Movement` and again, differently, in
  the client, and the two disagreed for a week without anything failing.
  """
  use ExUnit.Case, async: true

  alias Arena.Map.Movement
  alias Arena.Map.TileSemantics

  describe "class/1" do
    test "names the three states the tile grid actually has" do
      assert TileSemantics.class(0) == :walkable
      assert TileSemantics.class(1) == :solid
      assert TileSemantics.class(2) == :water
    end

    test "treats an unknown value as solid, because a wall is the safe guess" do
      assert TileSemantics.class(3) == :solid
      assert TileSemantics.class(255) == :solid
    end
  end

  describe "enterable?/2" do
    test "walkable ground is open to everyone" do
      assert TileSemantics.enterable?(0, false)
      assert TileSemantics.enterable?(0, true)
    end

    test "water needs a boat" do
      refute TileSemantics.enterable?(2, false)
      assert TileSemantics.enterable?(2, true)
    end

    test "solid is closed to everyone" do
      refute TileSemantics.enterable?(1, false)
      refute TileSemantics.enterable?(1, true)
    end

    test "nothing stops a boat on dry land, which is this server's behaviour today" do
      # Recorded deliberately. If this ever becomes false, the fixture and the client's
      # Tile::enterable must change in the same commit, and this test is where a reader
      # finds out that the asymmetry was known rather than overlooked.
      assert TileSemantics.enterable?(0, true)
    end
  end

  describe "requires_boat?/2 as Movement uses it" do
    test "is true only for water without a boat" do
      assert TileSemantics.requires_boat?(2, false)
      refute TileSemantics.requires_boat?(2, true)
      refute TileSemantics.requires_boat?(0, false)

      # Solid is excluded on purpose: TileGrid.move_entity/4 rejects those first, and
      # folding them in here would change which error a blocked move reports.
      refute TileSemantics.requires_boat?(1, false)
    end
  end

  describe "the transfer path does not check where it puts you" do
    test "an exit transfers a walker onto a water tile" do
      # The defect `ao_core::seam` counts four of in the corpus, proved through the code that
      # produces it rather than inferred from the map data. `check_tile_exit/5` looks up the
      # band tile the character stepped onto and emits a transfer to whatever the exit names.
      # It consults neither the destination tile nor `navigating`.
      exit_record = %{x: 88, y: 50, dest_map: 495, dest_x: 14, dest_y: 50}
      state = %{meta: %{tile_exit_map: %{{88, 50} => exit_record}}}
      entity = %{navigating: false}

      assert {^state, true, [{:transfer, 7, 495, 14, 50, ^entity}]} =
               Movement.check_tile_exit(state, 7, entity, 88, 50)

      # And the tile it hands them to is one they could never have walked onto.
      refute TileSemantics.enterable?(2, entity.navigating)
    end

    test "no exit at the tile means no transfer" do
      state = %{meta: %{tile_exit_map: %{}}}
      assert {^state, false, []} = Movement.check_tile_exit(state, 7, %{navigating: false}, 88, 50)
    end
  end
end
