defmodule Arena.Map.TileSemantics do
  @moduledoc """
  What a byte in the tile grid means, in one place.

  `Arena.Map.CsmParser.build_tile_grid/1` produces the grid and this module is the only
  statement of what its values mean. The rules used to live inline: a `tile_val == 2 and not
  entity.navigating` in `Arena.Map.Movement`, and a copy of the same idea in the Rust client.
  Two copies of a rule are two rules, and they diverged — the client read the grid as
  blocked/not-blocked for a week, which classified 278 maps as ocean, nine of them dry rock.

  So the rule is a function, `Arena.Map.Movement` calls it, and the cross-language fixture is
  generated by calling it too. A handwritten fixture can agree with a stale copy of a rule;
  one generated from the function that the server actually uses cannot.

  Values, as `build_tile_grid/1` writes them:

    * `0` — walkable ground
    * `1` — solid; blocked for everyone. Applied last by the parser, so it wins wherever
      both blocked data and water graphics cover a tile.
    * `2` — navigable water, derived from layer-1 GRH ranges and cancelled where layer 2
      puts a bridge over it

  Anything else is treated as solid: an unknown value is safer as a wall than as open ground.
  """

  @type class :: :walkable | :solid | :water

  @doc "The class of a tile value."
  @spec class(integer()) :: class()
  def class(0), do: :walkable
  def class(2), do: :water
  def class(_), do: :solid

  @doc """
  Whether a character may enter this tile.

  Note the asymmetry, which is the behaviour this server has today rather than an oversight
  in this function: water requires a boat, and nothing stops a boat on dry land. VB6 almost
  certainly disagreed. Changing it is a gameplay decision, and it belongs in one edit that
  changes this function, its test, and the regenerated fixture together — not in a client
  that quietly guesses a stricter rule and then mispredicts moves the server allows.
  """
  @spec enterable?(integer(), boolean()) :: boolean()
  def enterable?(tile_value, navigating?) do
    case class(tile_value) do
      :walkable -> true
      :water -> navigating?
      :solid -> false
    end
  end

  @doc """
  Whether this tile is water that the character cannot cross without a boat.

  The exact predicate `Arena.Map.Movement` needs, kept separate from `enterable?/2` so the
  movement path's behaviour is unchanged: solid tiles are already rejected by
  `TileGrid.move_entity/4` before this is reached, and folding them in here would change
  which error a blocked move reports.
  """
  @spec requires_boat?(integer(), boolean()) :: boolean()
  def requires_boat?(tile_value, navigating?) do
    class(tile_value) == :water and not navigating?
  end
end
